---
bioproject: PRJNA295401
category: Other
contrasts: []
description: ''
ena_first_public: 2016-01-05
ena_last_update: 2016-05-21
pubmed:
  26490224:
    - 'Rubio-Pe침a .. Cer칩n, 2015'
    - 'Modeling of autosomal-dominant retinitis pigmentosa in <i>Caenorhabditis elegans</i> uncovers a nexus between global impaired functioning of certain splicing factors and cell type-specific apoptosis. (Rubio-Pe침a .. Cer칩n, 2015)'
resource_links: []
rnaseqer_last_update: 2018-01-07
submitting_centre: 'Modelling human diseases in C. elegans, Cancer and Human Molecular Genetics, IDIBELL'
title: 'RNA-seq from animals treated with RNAi against prp-8, prp-6, and prp-31'
